export const ADD_IMAGE_DATA_TO_STORE = 'ADD_IMAGE_DATA_TO_STORE';
export const ADD_SLIDER_IMAGE_TO_STORE = 'ADD_SLIDER_IMAGE_TO_STORE';
export const UPDATE_CURRENT_INDEX = 'UPDATE_CURRENT_INDEX';
export const SET_IMAGE_IS_LOADED = 'SET_IMAGE_IS_LOADED';